### ISSUE TITLE
PhocaDownload backend file add

### ISSUE THREAD

**Issue by gruz** [gruz/NotificationAry#1]
@duvi
This is great, thank you!
 

Was it working for you on administrator as well?

I just tried to add a file from the administrator area on the demo website and on a live too, and I didn't get a notification.

Thanks!

**Comment by duvi** [comment]
Here's the scenario.

- log in to demo.duvinet.hu/administrator as demo user
- Components/PD/Files/New
- enter Title, select Category and Filename
- press Save & Close

My Super User accound "duvi" did not get a notification, although is subscribed to the rule.

**Comment by gruz** [comment]
Did you add the files as `duvi`? If yes, then you, as the author, obey other notification rules. When you change something and receive notes on it it can be useful when testing, but annoying on regular basis. 

I'd recommend adding users for different groups for testing. 
![2018_04_11_12_38_52](https://user-images.githubusercontent.com/422942/38608898-56cd152e-3d85-11e8-8796-1460fd5e697f.png)

**Comment by duvi** [comment]
I added the file as "demo". Neither "demo", nor "duvi" got a notification.

**Comment by gruz** [comment]
True, I'll take care of it.

**Comment by gruz** [comment]
The problem is the template. It should work if you either reload the template (but preserve your customized link), or just update context alias line: 
```
phocadownloadfile,com_phocadownload.phocadownloadfile
```

Check [screenshot](http://gruz.ml/images/x/2018_04_12_22_19_23_sp.png)

Let me know it it works to close the issue.
