### ISSUE TITLE
xml error in j3_plg_system_notificationary_0_2_17_alpha_build_37

### ISSUE THREAD

**Issue by duvi** [gruz/NotificationAry#2]
<filename>.gitignore</filename> should be removed from notificationary.xml, now the plugin fails to install.

**Comment by gruz** [comment]
Ok, will take care of it.

**Comment by gruz** [comment]
This cannot be reflected here, as I use my custom build script. But it seems I've solved the issue. So I close it. Reopen please, if you meet it later.
